"""initial schema

Revision ID: d6c5679eb05d
Revises: 
Create Date: 2026-09-21 14:33:50.254149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6c5679eb05d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promoter_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('store_key', sa.String(), nullable=False),
    sa.Column('parse_status', sa.String(), nullable=False),
    sa.Column('parse_error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', 'sha256')
    )
    op.create_table('promoter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('rera_promoter_ref', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('pan', sa.String(), nullable=True),
    sa.Column('registered_address', sa.String(), nullable=True),
    sa.Column('partners_or_directors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('source_document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state', 'rera_promoter_ref')
    )
    op.create_table('score_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('breakdown', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('input_source_document_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['promoter_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_membership',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('promoter_id', sa.Integer(), nullable=False),
    sa.Column('link_type', sa.String(), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['promoter_group.id'], ),
    sa.ForeignKeyConstraint(['promoter_id'], ['promoter.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'promoter_id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('rera_reg_no', sa.String(), nullable=False),
    sa.Column('promoter_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('locality', sa.String(), nullable=True),
    sa.Column('configurations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('carpet_area_range', sa.String(), nullable=True),
    sa.Column('registration_end_date', sa.Date(), nullable=True),
    sa.Column('extended_end_date', sa.Date(), nullable=True),
    sa.Column('source_document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['promoter_id'], ['promoter.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state', 'rera_reg_no')
    )
    op.create_table('complaint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promoter_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('complaint_ref', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('non_execution_applied', sa.Boolean(), nullable=False),
    sa.Column('filed_year', sa.Integer(), nullable=True),
    sa.Column('filed_month', sa.Integer(), nullable=True),
    sa.Column('order_url', sa.String(), nullable=True),
    sa.Column('source_document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['promoter_id'], ['promoter.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('promoter_id', 'complaint_ref')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complaint')
    op.drop_table('project')
    op.drop_table('group_membership')
    op.drop_table('score_snapshot')
    op.drop_table('promoter')
    op.drop_table('source_document')
    op.drop_table('promoter_group')
    # ### end Alembic commands ###
